### ISSUE TITLE
User Model Task

### ISSUE THREAD

**Issue by QuestionGuy** [DaniSchechter/VBeat2.0#13]
- [x] User Create
- [x] User Login
- [x] User Session
- [x] User Login UI
- [ ] User Search
- [ ] User Delete
- [ ] User Edit
- [ ] Verify username doesn't exist
- [ ] Verify email doesn't exist already
- [ ] Verify username matches restrictions
- [ ] Verify password matches restrictions
- [ ] User Model Error Handling

**Comment by QuestionGuy** [comment]
User create UI is made, now backend needs to be made

**Comment by QuestionGuy** [comment]
- [ ] Verify username doesn't exist
- [ ] Verify email doesn't exist already
- [ ] Verify username matches restrictions
- [ ] Verify password matches restrictions

**Comment by QuestionGuy** [comment]
Redirect once login is successful

**Comment by DaniSchechter** [comment]
Alex fixed redirection
