### ISSUE TITLE
Like error

### ISSUE THREAD

**Issue by DaniSchechter** [DaniSchechter/VBeat2.0#150]
For a scraped artist, who don't have LIKED SONGS playlist yet, there is like error:
1. The num of likes for the song does increase
2. The playlists LIKED SONGS gets created
BUT
3. The song doesn't get added to the playlist (probably we try to add before it is created)
4. Therefore, the liked button isn't colored in blue

5. Second like acts as expected

**Comment by QuestionGuy** [comment]
@alex-schechter fixed it. @DaniSchechter Can we close this?
