### ISSUE TITLE
handle logout

### ISSUE THREAD

**Issue by DaniSchechter** [DaniSchechter/VBeat2.0#60]
- [x] handle session termination in BE - req.session.userId should be restarted
**make sure UI doesnt break including:**
- [x] non logged-in users shouldn't edit, delete, like, add to playlist
(buttons in tool bar shouldn't be visible both in song list and song-details)
- [x] non logged-in users should see only 2 buttons in the header (log in, sign up)
- [x] logged-in USER NOT ARTIST should be able to like, add to playlist not edit/ delete and not create a new song
- [x] logged-in ARTIST should be able to like, add to playlist, edit and delete only his songs
- [x] logged-in USER AND ARTIST shouldn't see log-in and signup buttons

**Comment by QuestionGuy** [comment]
Like button is already broken

**Comment by QuestionGuy** [comment]
logged in artist can't edit/delete his own songs.

**Comment by QuestionGuy** [comment]
@DaniSchechter

**Comment by QuestionGuy** [comment]
- [ ] Like button doesn't show up for artists
- [ ] Logged in artist can't edit his songs
- [ ] Logged in artist can't delete his songs
