### ISSUE TITLE
check in the BE if user id is null

### ISSUE THREAD

**Issue by alex-schechter** [DaniSchechter/VBeat2.0#88]

**Comment by QuestionGuy** [comment]
routes/playlists.js:11:        UserId: req.session.userId,
routes/playlists.js:30:    Playlist.find({UserId: req.session.userId })
routes/playlists.js:59:    Playlist.findOne({UserId:req.session.userId,  name: req.params.name})
routes/playlists.js:77:    const playlistQuery = Playlist.find({UserId: req.session.userId });
routes/playlists.js:130:        UserId: req.session.userId,
routes/songs.js:31:    console.log(`user seesion: ${req.session.userId}`);
routes/users.js:14:	req.session.userId = null;
routes/users.js:36:        req.session.userId = newUser._id;
routes/users.js:53:            req.session.userId = resultData[0]._id;
routes/users.js:91:    User.findOne({_id:req.session.userId})

**Comment by QuestionGuy** [comment]
https://github.com/DaniSchechter/VBeat2.0/pull/94
